### ISSUE TITLE
NotBefore and Expiration should be evaluated against UTC time

### ISSUE THREAD

**Issue by eliquious** [SermoDigital/jose#21]
This is a great library. Thanks for writing it. +1

However, I just realized the claims are evaluated against [local time](https://github.com/SermoDigital/jose/blob/2a2a7005e242469734d8d0d110f4bb657bb67759/jws/jwt.go#L88). The spec declares the `nbf` and `exp` to be in UNIX time. This could cause very hard-to-diagnose issues for invalid JWTs.

**Comment by EricLagergren** [comment]
nice catch! i won't be able to get to this until friday at the earliest -- could you possibly submit a PR? if not it's totally cool and I'll get around to it when i've a chance.

the patch would be `time.Now().UTC()` or using `func now() time.Time { return time.Now().UTC() }` instead of calling the UTC method every invocation.

**Comment by jaymecd** [comment]
Any updates so far?

**Comment by EricLagergren** [comment]
@jaymecd Pushing a commit right now.

**Comment by EricLagergren** [comment]
All done! https://github.com/SermoDigital/jose/commit/389fea327ef076853db8fae03a0f38e30e6092ab
