### ISSUE TITLE
JWT token validation

### ISSUE THREAD

**Issue by romanoff** [SermoDigital/jose#22]
Hello. Is there a way to validate that token key matches the original key it was signed with? (As I understand, this is called signature validation). I thought that this code would do the trick:

```go
package main

import (
	"fmt"
	"github.com/SermoDigital/jose/crypto"
	"github.com/SermoDigital/jose/jws"
	"time"
)

func main() {
	mySigningKey := `secret`
	claims := jws.Claims{}
	claims.Set("hello", "world")
	claims.SetExpiration(time.Now().Add(time.Hour * 72))
	claims.SetIssuedAt(time.Now())
	claims.SetIssuer("google.com")
	token := jws.NewJWT(claims, crypto.SigningMethodHS256)
	serializedToken, err := token.Serialize([]byte(mySigningKey))
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(string(serializedToken))
	
	newToken, err := jws.ParseJWT([]byte(string(serializedToken)))
	if err != nil {
		fmt.Println(err)
		return
	}
	fmt.Println(newToken.Validate(mySigningKey, crypto.SigningMethodHS256))
}

```

But it reports that key is invalid. This validation can also be seen at jwt.io in debugging mode.

**Comment by EricLagergren** [comment]
The issue is `mySigningKey` is a string but if you check the code it
asserts that it's a []byte, thus invalid key.

When you serialize the token you convert your key into a byte slice, but
you don't when you verify.

I know the Validate method takes an interface{}, do the documentation
should be better. Also, the error returned from Verify when the types don't
match should be better as well.

My apologies.

**Comment by romanoff** [comment]
This worked. Thanks a lot!
