### ISSUE TITLE
Code examples please

### ISSUE THREAD

**Issue by elgs** [SermoDigital/jose#4]
Some code examples in the `README.md` would be helpful and appreciated.

**Comment by deviantmk** [comment]
true, in the meantime you can check the tests for example code

**Comment by EricLagergren** [comment]
Re What @deviantmk said:

check here: https://github.com/SermoDigital/jose/blob/master/jws/jwt_test.go for testing examples.

**Comment by yeahia2508** [comment]
please add some example code.. as a golang  newbie it's hard to understand this library from test code.

**Comment by ifraixedes** [comment]
I'm quite struggling to work with this library because the separation between JWT and JWS with no easy to convert between each other make the things very complicated.

I've spent quite a few time with it for a simple token validation with a "kid" protected header value which I want to check that it's present in the token; when I thought that I've got it, I struggle to generate a token in the test to test that validation.

As a result, I've got the PR #24

The work in this library is much appreciated because it's open source with the very open MIT license, but I would like to know if this library has been used to build something (difficult to see clear after the time that I need to do something which should be simple) and if you consider that it's implemented in idiomatic GO. Nothing wrong, but that information would help to people to make better decisions on using it and potentially encourage people to contribute improving it.

**Comment by Komosa** [comment]
Tests should rather check if ANY (instead of ALL) expectations are broken, right?
https://github.com/SermoDigital/jose/blob/master/jws/jwt_test.go#L40

**Comment by EricLagergren** [comment]
@ifraixedes I'll put up some examples inside the documentation today so it'll show up on godoc.

**Comment by nanoninja** [comment]
I've put a [example](https://gist.github.com/nanoninja/57500c3f492253f33877080c093e982c) to use [Jose](https://github.com/SermoDigital/jose) onto github. It's not very optimized but it works.

**Comment by koalalorenzo** [comment]
ETA on examples? 👍  :)

**Comment by robbyoconnor** [comment]
The code and tests were more than sufficient :)

**Comment by elgs** [comment]
@robbyoconnor yay, they are better than nothing. When they are good, they could be really good.

@nanoninja way to go!!! Thank you for the samples for human beings.

**Comment by koalalorenzo** [comment]
This issue is about the Readme file code examples not just the documentation/examples in tests....
Please re-open.

**Comment by martinreus** [comment]
Code comments on how to setup a simple encode/decode example would help a lot. This library really seems well written!
