### ISSUE TITLE
SetExpiration, SetIssuedAt, ... type change

### ISSUE THREAD

**Issue by ivoviz** [SermoDigital/jose#9]
Hey!

First of all: finally a real simple jwt lib! Thanks!

Secondly: as mentioned in the title, should those exported functions receive float64 vars? Can't see any reason why it couldn't be int64.

**Comment by EricLagergren** [comment]
Thanks!

[Section 2](https://tools.ietf.org/html/rfc7519#section-2) of the JWT spec defines 'NumericDate' as 

```
 A JSON numeric value representing the number of seconds from
      1970-01-01T00:00:00Z UTC until the specified UTC date/time,
      ignoring leap seconds. 
```

Per the `exp`, `iat`, etc. claims are supposed to be `NumericDate`s. I don't remember why I chose float64, exactly, but I think it was because JavaScript (and thus JSON) numbers are IEEE-754 floating point numbers (float64s).

I can't think of any reason why it couldn't be int64, but at this point I don't want to make any large breaking changes to the API, which float64 -> int64 would be.

Sorry about that.

**Comment by ivoviz** [comment]
No worries, it doesn't bother me at all! I was just curious since I didn't see the reason behind it.

**Comment by magiconair** [comment]
You could change the signature to `interface{}` and allow both float64, int and int64.

**Comment by magiconair** [comment]
I think also given the fact that you don't provide examples on the README yet the chance the people just blindly `go get` your lib and use it is pretty slim. It took me a fair amount of digging to understand how it all fits together. I would prefer a cleaner interface as well. People who integrated your code will know where to look since they had to.

**Comment by magiconair** [comment]
In thinking about this a bit more I think the fields that return timestamps (Expiration, IssuedAt, NotBefore) should actually use `time.Time` values instead of raw values. Since these are part of the JWT spec and other implementations depend on their format you should treat them as time values and not as numbers.
